* Battle
** Strip away elements system
I need to make things better in general, and the elements system is confusingly
implemented and sort of useless.
** Eliminate use of battle.state
Change location of queue to player actor. Must relocate all mutable state here.
May become more clear if scene system is replaced.
** Reduce inheritance...replace with parameters?
** Navi Enemy
I have some boss designs on paper, I should probably get some feedback on them.
It's that or determine what navi AI or animation features I want to put into
place, and make a simple enemy that has all of those traits.
** netplay
Where to begin? I may want to separate a server/client somehow. I should start
by sorting out which data needs to be shared between clients.
** chip selector for debugging
I just want a list of all chips and be able to put them into queue easily.
** possible feature: pvp cust delay
When one player wants to cust, display a timer on the other players'
cust menu; give them 10 seconds to finish before the game autostarts.
** Battle editor GUI
The idea here is that battles would be easier to edit with a UI, rather than in
the current primitive format. This is likely to save effort in the long run, and
create a sense of unity by having visual lists of enemies, maybe even previews.
* World map
** Display dialog box w/script
** Move actors to position w/script
** Move actors along path w/script
** Pause screen
** Saving
I need a plan on how to implement the save system.
* Other Stuff
** handling music
I should recover my old music from lanparty-code, get some feedback on it in
discord or possibly other locations (upload to soundcloud is ideal), and
ultimately decide whether I want a composer for me, or what. hi lorna?
** sound effects
I should determine sound architecture. Similar to image, or channel-based
approach? etc.
** Replace scene stack system with simpler loop assignments
   Must also use this to fix bug in customization dialog box, where local pvp
   freezes. There's a problem where the 'pause' screen for battle just calls
   scene.pop twice to exit the scene, and that's really hacky but I see no
   better way.
** Exe builder
** Fix video dumping
I reorganized all the folders and video dumping might not work. I might also
make it nicer.
