-- All ingame chips and their 'headers'

return {
   {'Triangle',
    desc={'Shoot out',
          'some triangle.'},
    elem = 1, damage = 80,
    class = 'triangle',
   },
   {'Boots',
    desc={'Fire off a',
          'pair of boots.'},
    elem = 2, damage = 40,
    class = 'boots',
   },
   {'WhlCrate',
    desc={'Damage makes',
          'it roll.'},
    elem = 2, damage = 40,
    class = 'wheel_crate',
   },
   {'PoisDrop',
    desc={'Poison 3',
          'spaces ahead.'},
    elem = 3,
    class = 'poison_drop',
   },
}
