return {
   {"Boots", ltr="a"},
   {"Boots", ltr="a"},
   {"Boots", ltr="a"},
   {"Boots", ltr="b"},
   {"Boots", ltr="b"},
   {"Boots", ltr="b"},
   {"Boots", ltr="b"},
   {"Boots", ltr="b"},
   {"Boots", ltr="b"},

   {"Triangle", ltr="a"},
   {"Triangle", ltr="a"},
   {"Triangle", ltr="a"},
   {"Triangle", ltr="a"},
   {"Triangle", ltr="a"},
   {"Triangle", ltr="b"},
   {"Triangle", ltr="b"},
   {"Triangle", ltr="b"},
   {"Triangle", ltr="b"},

   {"PoisDrop", ltr="a"},
   {"PoisDrop", ltr="a"},
   {"PoisDrop", ltr="a"},
   {"PoisDrop", ltr="a"},
   {"PoisDrop", ltr="a"},
   {"PoisDrop", ltr="a"},

   {"WhlCrate", ltr="b"},
   {"WhlCrate", ltr="b"},
   {"WhlCrate", ltr="b"},
   {"WhlCrate", ltr="b"},
   {"WhlCrate", ltr="b"},
   {"WhlCrate", ltr="b"},
}
