return {
   {"Boots", "a"},
   {"Boots", "a"},
   {"Boots", "a"},
   {"Boots", "a"},
   {"Boots", "a"},
   {"Boots", "b"},
   {"Boots", "b"},
   {"Boots", "b"},
   {"Boots", "b"},

   {"Triangle", "a"},
   {"Triangle", "a"},
   {"Triangle", "a"},
   {"Triangle", "a"},
   {"Triangle", "a"},
   {"Triangle", "b"},
   {"Triangle", "b"},
   {"Triangle", "b"},
   {"Triangle", "b"},

   {"PoisDrop", "a"},
   {"PoisDrop", "a"},
   {"PoisDrop", "a"},
   {"PoisDrop", "a"},
   {"PoisDrop", "a"},
   {"PoisDrop", "a"},

   {"WhlCrate", "b"},
   {"WhlCrate", "b"},
   {"WhlCrate", "b"},
   {"WhlCrate", "b"},
   {"WhlCrate", "b"},
   {"WhlCrate", "b"},
}
